spring:
  application:
    name: test-canal
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    username: canal
    password: canal
    url: jdbc:mysql://tcloud:3306/canal?useUnicode=true&characterEncoding=utf-8&serverTimezone=GMT
  # redis 配置
  redis:
    # 地址
    host: tcloud
    # 端口，默认为6379
    port: 6379
    # 数据库索引
    database: 1
    # 密码
    password:
    # 连接超时时间
    timeout: 10s
    lettuce:
      pool:
        # 连接池中的最小空闲连接
        min-idle: 0
        # 连接池中的最大空闲连接
        max-idle: 8
        # 连接池的最大数据库连接数
        max-active: 8
        # #连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: -1ms

# 定义与Canal服务器的连接参数
canal:
  # canal服务器的地址和端口号
  server: tcloud:11111
  # 数据目的地，标识数据的变化流向
  destination: example
logging:
  level:
    top.javatool.canal.client.client: OFF
